language: node_js
node_js:
  - "7"

os:
  - linux
#  - osx # removed OSX because macOS builds on travisci are becoming unstable
dist: trusty # to use Ubuntu 14.04
#osx_image: xcode8.3 # to use macOS Sierra 10.12
sudo: false

git:
  depth: 3

branches:
  except:
    - v4 # skip experimental v4 branch

env:
  global:
    # -----------------------------------------
    # Only for server side
    # encrypted oauth secret keys
    # GOOGLE_CLIENT_SECRET
    - secure: XLfh8kRq6E5nZN6lggCn6R/ugEcHwzSMjs7sUuZnJgMrq7vBCZhzGX6wJ0HB4No/GsbuRiWkp3FyIzhJc8b2XNUqFFqWnKnwnzT5rcrjoXGnoUapSqkFV1ditmr+bFop1KP7PtuVdkMt9CwPaLkRby3wmfkgH6GGQBDFiWOqfhrjUV3D54V1x+cgC7J8Gg5oWoJwAP4pgvSm+JjFi7hgXndgx3b22avD/LPWcMiLCvmbt4ciSKcicQm50fAvBTGKcTESkhKR2LKZIOlc6rFtF/N4x910WA1P5Hj+zKJDOY/NvdtRdftSD36pjOm6XrDyINh6yoTpoHscFMPUG3DmpHngaisRAgHoIgBIXwf6/AhWLJoyltUFtlHbQ822xC11Q3wTgSGIYccOHlvYOy7t6JOOmJbTGwZJHgWMokmbzmv3FN4uPjm3ZwtAc51vp6AVAo9TbEOYoioVkI8x9GKFefXYNFfPTFiVLD3UCvJWFF5Y3A/MTZdq+ZJsAKQkGcm49CNTC31JLfM94ZDPQjVIIiW0TXIBlnIzwUSVamH8OS/NjBV4UQKmiUP4ovQgmkfinC1UkceKjCg1nzx/JUTaQo1wepy+nP4i4JwfBIRPpPeXKBd47den8ijaLG4Im6es7ZBvnbaUMjMB8HO2ZSVINa21medcYj1GmyottQKLrwM=
    # FACEBOOK_APP_SECRET
    - secure: Jd2GZo3iCbylESMIwgLSfq+oCtsolbazfkCAsUmjtIVVzHjizl4k9sfHDOFR9TbjKaxuelwokCIStDvnKHVVSVLSZapvGlwgy3iWX4jsVcKi7hWgrB/v1v/Fw680n0dH0BxXNacrkREVnwqQpgkRSMPoG/lsHkz1mPauNczidzGzMWxTANypyjYzx9Rg5wk2MqRMmOleIt3G7bwWsLFpXTns0CtNo/gglCz4BVFws/CnYtQZ+lb3pssmVyhdQnfObQxkoLOebMElTZkcyTJBoto843QGJvJGwjJ1V8494JDnnPmyFUtLpd0ueyhB/clQZY5ZiouulOVCUYIf7Qjwldq/x2eiZyxqHsTVptMFOvWW4PyW5ZhpUbA0fEck7Q4aBry33VozNkRvglifnFExB2uiBcx/LNAJNY+E7/tRHWKH01DtRrozMBOxlbCWoI5w4CUNoknhnQkGCkG0IokPZQC9AZLeJUSleCuEnzBUyTK3YGsGqjYHA7BKqiVO9o+4x6+TBGN8OyNpBXvlRkxZXfW/4nQwMe1218mYjv6JTztN9lVozDmyfQcSNCzf+pp2qldkYw1/YC7nl8vWQPOLj32l9dHdsQxDJek7elNOv/a/GjEaj03ItgjZzykQ46NZE19a6yXZCRVBgLaCuk4o8CWx6gyoogCuCDTG75emDdk=
    # GITHUB_CLIENT_SECRET
    - secure: BVDW1m9Didg56Cp+kigZLCisLGPBBWEm4P7Goq2j5iz/b6C/2YVM+CJVetMOgjYxY66bifXzUR6gcr4DYTLWRtP3C2fnBZXphJXFjI3R04uxSCdukh7Uc0zqDfPvXzlXh40QD3647AuUCYZmgePe2mjrd4gHbE2VGyOTa/ZMizxrJPnCKhtz6AhMaZHHSX5Pjv2GRvoXa3bLs9EtSYditJHlkIwb7MqTL54snIRmCvLXwVl2LGc9SmTMfEnYUSgWn7dbbvUi8dCW05RPQaebRutEQ9Nr616wnOOYWX4tHjq7hYO0PZCUwo8t6ZpKv5r2dXB1v5ziX1toIfiUA2qLKMFYM1Gl3Tyy1jkspRW0bq7jL/DjPElcjntpfSD6Jnmg2BlYjZdVnfw5BhWhaqz7/QByVwHh91xoqwEqQjgHBxmVE3G6gQcTJyei9Ja958Kl6VMwP/aGQu+lQemSiGq2uCNsTQfYlOUOsFCVrC+RrRj2vHRfqq3hkQdGmv1xIuF/6xmtt2xUMLujSjHocNBLxkMsTq6H6AUqLdM4flv2JdXrXK/c4hkpEOLLWwhGyjroRtYUV9RBfvL3/HDFhLdtfeCvbyO1P+RSmHT2Xilamay09swe1Z9D02GcrSS8PMxT0rRKltVLR0AKGFLkLxd6ERu/ViXydgOVsd2e1wLhDk0=
    # TWITTER_CONSUMER_SECRET
    - secure: a4l2JHHaKYeGJf+koV3D9R0YII8+MtT5cv9Tjjq1liANg2/8RNJlLCTGw/C6mwZnWw0rnC0Xqb7Qsq5RN3P1ezf6MqdQO/waROpZdD8vLUQbMi528qu9s1OZIBg4HIBWGvnD6W8OqUW9AjUPf+bzXwwojRvNgOdxHF1WvC807cWo1iW3/pbQP+U5sGMAsm0vNPzQXrVgPcCRA83UZ/yXl8GMSsppoX8/Y8rxz6IoJbWmkNO0cOc4t+1zGesPJVd7n/SpVZi9qKn+Ky2ZvoCITceA3JYOp2qZTX//m0DJWOf+aPHi4nxTlxnvdgZWjX0VF2FddUNEJOX7Ztw7p2vqsxJD9pcobrISyOe2/kbIAinRwMO5scsCoI/Vxw6iuy604pvkbMO6Hf6FTStoqHUMDUt1nkO2gMHfkbYTMuEMER/OX5hSan98Nwo5sQPf49W0ct6tA9HpRW9EcawqCW+zEZK47ZNZ5AjvlTYDyWDzkgFOpPdz45KnywILa14utfmTIhfBz6GuuFfnmc+VAbaDM0EZTZAhduOlptwMUIciBB3PEFwh/0g3WzYLdqeY0B3Qu0XZS0ML/5+yNWOwvPDeS6OxN24WjQpOD4X+Wmsj0AM7Qod3rD09efPG2kuOwe8Vck66DT/dbjCg054rwHZeKHCEyh11SfOYek9L7A867j4=
    # LINKEDIN_CLIENT_SECRET
    - secure: XQFOEJWQV9iX6SMUMdx1wK6N1RESs5ksAd0ae0zffb+yFlANwVhBAwo4jvSh0SlOEozgW31pqN6rbA6qKQf44NSk/EgLtq/CYuJqvYoOg1R8YovmTNyHIydGYgixQbyKGRmAZ3dZSnqknFSsNEfPRRR/C1KLYFV+hvqUAijdh6CrvevnLvYJeLJhhZLUZSws6Z/jxoW5/35CHH5HuTWfNH20zKDyM4QWSoQr/iOQutZa5UuCe1IUqVUP6jqRdPgFxSXT4UHsyBzieeQhof+NgmuW0zAXmei5r97mloMnfo1NEiGoZ3W7Df+Ngd2Q+/4PyfLK3iBH/gQwMRxBRa1QgYUhoPtw9YTNE/AKmtb5mELPevQgqNH1DoSCghoK638uBU3X4LYR+3i0XVK4iPRBjN8ktPcns9jc03QxtKPdU4Cx+JEmf/aU+cCYxYhoZ2AqZ1TLVAP2lJJPtE555lLGdTLOy4B+uU19G82ofJ29Tk1Yc/Kw0q4I0Dmt91u7CxQNBq24wR596VrontUhSMh2T+lZAHpXfeaWJLcBMZrYcYCr3BCWkzUyW4xwLft0mNv+abafE0N4exXuTbm1qeUx0hvlpo+i4E/LUeP9xGYBRR2DtIZFSgophFHL4LzaQg4cHXwDNSqI7A6KhUh7341/Oz/EFhrCUGF/bEZ4MTN7dcw=
    # -----------------------------------------

    # -----------------------------------------
    # Only for client side used by e2e tests.
    # e2e login 3dparty services encrypted variables
    # GITHUB_USER_E2E
    - secure: Xm0NB2+iQEtmZb0Xq0zyPkZoZhFFRlBoN8tJi4s3gfCYHtaQDv5caAYaC1lNWNCTXgw7xsQURqAY/4VFCapv2zoSPWIouUSRpviSRItRROYg7NKhLzeTtp/eGDzXIwsJR3+IHmyUQ9i/i5VTF/hXLKDI49rfCEqA7ER70cYo11lTtBJBiQh0QsdnOzG8DbRg5LfpzCESIy0vmD+xjgQ/vRZcPMvcdx7/7zVA0LASjqeCkKQj6Vr0JMO8MH41+WdshPCP7KO5hfzLOQ+w/mAbP1dtjEP+mdyNFfuFvC5iOtiM0A2X+pNjQ4GXTsjofijR9g0sDDKIjN881Ko6kUUoGXK4GTSYxG/Xi6majx+kmsV8UfJFAXcTttszH9CWHVTql/Sr1ezE/jCN8qmM4t3jIZ+kQ5HLP7GHW8kV3HML2QxWvQs2s2w+5ekKkOkh4yQUNKce40lV6Z7/nw6R2uG28NifFiXO3eTg9QxtBzM+dIhslVBRmcRJ0kOqlFUeRwm9OOFTaFBogIpNjqPOfr517igNShYTg4bn39goOL3iTi8fpobEDygV4kI3s8ZyPEz8eMl2czURXEPjgo3bp5K9CzhKVP3DZ88Q7Ug2edh2ZTDW/ZcaV6FARpnmEJlmsgKMWpdDpN969xxwppQzSy1JwUibBQPvZLpGFFWn1RSXk7I=
    # GITHUB_PWD_E2E
    - secure: QHqm0Ae4xSt+5pIMoQjDOZLZy1aItQxJ/QgDWjNq34ITkHoteSSqggE6uOjBfWMJPng78l4wO7bBf2rDQ5St/BCGk3yJdntrePFQSna4/p1uBexQm3qVqefWIQpp7k4BvEnbAXF5Xj7Ptg6xdh/RtHvyeWtyEuJKhTfJYZFO/ypklndqY30eysziJFP146GE8WblDeo0Qf27xFBG92/h0h9xyTMZ4ixWLAp+2MpKPGFtv3Wgx1wnjVa1QKwfTOP14Vfj5lKh0RQ5/ojag1GS68rzCo2/0qEveOoFrfr7g0Jt1h7GUPE9VG+/8131T1rK4UZ87bUiUJ/hZtPz0SmHf+hnthOixbQPpu9BnXsJAu2/82lZAhqliN/ZXBiAwFuxtIBF5dfd8AVNcJQ6GncWdngIRYCsy0NnobQchRrC/t96u5MuKmJqzCLg4+W9VUcm2j6KVbzM0ojPhoItZNl5n1aD3T67bOiLZAJI/SlaJNmgNdCisqvzM1fLpje5OV7viGxLOdBmroIQey6md1gDllvtDS7OVA5R0V8MMITJHXFo9o77Xy8HeZrYnWiHaTJmszHt/bLZU0//JpUIzASNedy2WGl1uXhI3vuc91B+09kG0w8008tYCVF9AAO6nhutC1V3V2ktd1mL4PHxrGNy/jmX50Obdq/RMMBs292GHAE=
    # GOOGLE_USER_E2E
    - secure: aGDkhrhnQL47HJs1JgEH/BxDdlZQcjbb+jAUK8uuNeQNujNXR3tI9yWn7GH+7aK8X9vEruFRQJkMqy6UaabltTqJQ+3lcGChnuNgF0inKWjWWCZY9HK4W9EL9yFNOTfLs/cFWLtsyY0p+s/svWQH2OKkSYHSUjmCV41lsJDjyzrJnCr1EZBLFSRmjR0+Y2kQuX+x5p/F9sCakOtzKlceSNCk4H+Pj4KRtJ6wXVfbYRdYhhFtbSgE7SLgmiIM/xy8ZwWjMoI7Ihr2kWnKg+VPdmJMfU/BWJiFQcl4BqH+3xPZmzp4X9c0U73zXEcBG/aJiECBzaTu1U1rcfOb3ZKz/aTdna6NchP6sAZV77hguF8e5JhDdtjMP05gtnXwmXTccwLXVzmZ0+T3ggqB8EAfzZTpuKAP2oA9BoXa5plJYbeaqN3XUQvpZ6js0W5ovnNnkLMhoVLemwVRwgpBeNrK8X1x2Ym/OSRrUFZlzwmYcCL4XNnVQrDLhDEWHDkMKTSAkQHL7wggfH3gC9lfn9Pm5NjllHBfVN2mVuKb3/liJLEHKfeQIj/pDGzMaI/6a5jIJv58wD/geZLZu3zV2iHatk98zv/7RJ3NKEShunleK+RVwG4ola7lWl+0QW2fFtBmNhdVVX9V++6GGbKfcJehEDqYVUSpZDBR/p9NUjXw0Ho=
    # GOOGLE_PWD_E2E
    - secure: MUAxTXjpGM099njsZNdnPNWt4EKeA4UesKLdAHkMSRbtwjOSe7fOYTW53achj764IIQFvzoshjVr1SxW2+QDOrrswV5ZFYtF2MTLzG8+AhDvj33ppbtvor/Gq2XzFISWun58sW8NHxpDOyIvF3G5Tn6GafReEzuf8f657IJw9b2RYTNgGeNz2CiikgMup21WWUwMdGsFRvkA1cuwgOKdO6I7vgQEQXcq/vsuL5co8FzxPBRaw7PWZASE67RWUSWJSW4rmkvFGD19rO123//6BPM27G6WDZUcMA38ucRY8G41ICYX4Ib/LtvLBsG34E/FDTD74SLY5IMZbN8VawIPMxX8o8+bgKIN9+xP5AtCVVmShO0FcOGvy59Qdl3OK41ghkkvKIUUvXEkSZhx+2sLU65eMDArUS/Xp1yD3UmnAruWJ5wVFPkMMeW/bEN5MFZvkIQ3BSLNfb3nCvCPhxKukopdUppbin3xUwz0cdbxqPpWfevGSWhqZEXtY/YRgFf1KiK2SUuUi1SaW005U9NAzcAHWwMqGmV8R6ie7SY5oljvXML3ByNA5lNMI61fFUgr9I6qzXnpvlz5RhNdlr5PsV1j1rXZAj7X71IT4aw/+smrM/AgK63HcGuRtbw3SuW4RH2io+BV9QUGTgLBBZTqsI7CqO5zuHIlShpi0Uh063g=
    # FACEBOOK_USER_E2E
    - secure: Z2i6ofwiEsCE6If+yp5BDQj3c7d3hzA9oCZG26Ns49f7aIxZLOgZGoDx59bEpZw3GfnSe316P0jPSaCyVZ4TI4wyH1HJRrOpc0bm/9TA5IIRAWuUHA8/6nbrYjnEHxWfIfXJR+P/IqDCsTywp/BPUoBsyiZFaImp1yxw8O3UlxDgmXU/MqLNAaAtJtOifaArcrrGL9FEhHYAYngNnL7rDZgHUwFFryllLR+fZtU6fM1/c1ofywFTDjmQ/ot2cV2XuujkCQtbd+26gD9o9/iXbaTEM7G4pNSKurVv+70l7Y7HQnwn8nCHP5F+PVIHD8QCwTFH+Tf7eMj1iZ2d2n9gG2ZO6DzE13HQugH0pqiaASFUy39m5/iKY+E1BOQDR6PMDaqNOmogQb8wCh1EiednVxxIaGpiAoOrFMaDhBbzlf5uDvYvVL1CyluiJXJdSEjGhSSKMIE0LZ7CbnOb578UwVNT19aTP+ZJVIY9f9w+IUexerzafhlFzb/vfqVRQ/9D3AyW3tOcZyFJBaCZogjb63I3Wfai21GPLCfZ/Me13Fx7E/M5sSaar6rcMVQ4DLNlRhXwXaWMxoTSYxmm/mdd+gOmDq59tQBVyB3EW0UzdCV/6leSpdcaY82BWmtJMU0lIh84aYQKbrzMAQZuMveYidZoO/qv02RHGwoa+bz5pjM=
    # FACEBOOK_PWD_E2E
    - secure: MDHCzokDsKx+6vbkUByOt5L1H5WMEyYyk5HCkP6p/lenGurHPsXe54hvuoHW5kk67uhRQjc2fCRQJ53dcN6Uva7ogxc0VL7uZj5EXxt27lSzhfA8P41iF2C1yt3iKJOAgecYV5+4tDbwG2IFESCVdOo0Q0vmEZxCqB+BbcdF/xUt4qODCwvF1pMWxV1Eb+SMusrW3ZTpLulgbj3AE7eQF+sU+Y4k+/rvfZn5FbtbORSyFxWO9FJG+Of/sxzJECQqQ/JNlLt3jAJ8e6gGThnOoYx/W6QSVDHfTyWPKh1rd+Mr3GVrVySQKxyHTIDBysxqY761dLZ09pCvL6qF6u0igZY89dx2cWHuyti+N9gVcbD/7JyDKsVrvUUQNGxmtcegZftAGhChUb9CmdMhEZ+cZGhRytmPa2OBDaJx2npy3BdFzJ1+f4ZE3TVq0owz7IgoA2eabgFPMawXlCha1kJmj8vfOs/sai3Vobn/NF47prtkxjVfLNSdbT2KrNP4HFEw6s3iEw9ymrWdVDMxI8zoogOJ9m4T4uJm1lPY47chZ3OuiaGS5gm5GnPDVmFZeNRZxPi0MjWbrTNN1vUSFUivYqzMBFf/T/ZYxd0GFx6mjes+M5UWBZhz46HQKEcWrs6m94LGDN5pzW3dplBD/PFBkU5HkADkpMk75PVoTXSOzp4=
    # -----------------------------------------

    # CODECLIMATE
    - secure: Rov9tYDaMYPBUeWDtD43S9h3llaljjMB0Khdi7P+kbkYOUPCm+Ol1Sr7nS+lwOQpF/3T1kva2OQ/LWkOM8kSng86EkMviEGQXpdlGRxP9clo8qmxyfbcKID5Q/a29kOIbkbbhx9cGFoepEjo+5T+Ya7GbbXIyMt1PNTCy5eLXnfU8BE/G3Ib8eVNBxGANiOuBTkKfzTyajH+pcsj0Wvr2Po/PjSIwYk6EfCzsYWbLDxjo86w7hD7F5OtjxPJTsYz3K1OwdneaUJ3bYLrGqpNewIfR4gASNTB4fBio0ZdBZ44UulKo6rO7tUMMQdCGm9+c54XeVGigJE9uhz8Fcim3FpfY9jraT9dhp5xPgvDl0OC/NVvHAGumak67X4Vkui5dAGGqbfNGfnWRvzkar/Xj3QpO7UJ0VEp2nFmZqgwE9CHhi+xMAh2+C5aoVsvtdb8LiACnN0YOfrMQvkoX2JGoGrLuJGJSTC3fRiLFIvWnX73L7+XKlrRUceoroyQ6WXEPkUbrtVtTN/yE0CVJmpVS1oE4Nre3zvOQAtIxGJWbk2rYTQ95C7cixAeo7ucFnX3J6YrSiTm0Ny+smdgv2KkXX8Q+UY0JG10BN3tHc67gqpvsaAPQaPGq4KF/jngE4a5H+skzpTnPRU0sozY4uNDXwGZmo4va03NFk6XVMk9rzo=
    # COVERALLS
    - secure: EtPvv9j3yZ8UjlloTx/5UIeRTIc4lSBirjhEKrOEDz5AVTBy71ndwOPo/pOg9sG6NclaXOZpYeVxw5LtsoX9fNW7fQZzkkENfYK7S0TgNrcAYfoAdkvV7IdjU0UkQG7hzSqT14Ad+//trfA/ExERHP/yQ6UhJ/wZRx/z4jQORgC/CtoB9nPugO04Wl+nzL9hS68Eh6NdVwEBNVNDjaNgpONfes8n5cNsGK90O9IVwGqleLsJ+nk3ZIit4zWHNkyxN22an0s8Cql/l+WlQlr2LlJG1iYVFyQALVqgcSOn3LQBDWW2FDEFZO40zKPKwvymTFezP+UAOupBtHTWnF2he5fNgPDYpc27QyKrxp7yfKFRtwSlAY2ONTNtzQ/eJmuSF8QKDm5oh9za9+SnxRlbNhG0hcYtIBjYVp2E8ocVqLd2LWanfFDbUI5Qij6aZTyRXsHGqgY6gpAo6zAToOfSXCxFXW8Y9p4KQszcxSenvCHxn9H08A8HJipsN3PJAHex/ZD4Kw6SzerC0XKvnhhg2jmasamjlLy4mlY4xlIkGns7PF+3818nlw9Naans83+fB8ngy+GbHC1vOoKO0QzE0ZorEFEt9t6wADFdOnZvFZ09MHz90bOUryUC6OT2JO44t9ES66oLE+8e9yheCgKyTpnEHgfvSaOGqEmzMGoCTgY=

services:
  - mongodb
  - redis-server

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

matrix:
  fast_finish: true

before_install:
  - source travisci/before_install.sh
install:
  - bash travisci/install.sh
after_install:
  - npm rebuild node-sass
before_script:
  - source travisci/before_script.sh # starts in the same shell
script:
  - bash travisci/script.sh
after_success:
  - source travisci/after_success.sh
after_script:
  - bash travisci/after_script.sh

cache:
  apt: true
  bundler: true
  directories:
    - node_modules