npm install -g karma-cli
npm install -g webpack
npm install -g typescript
npm install -g typings
npm install -g remap-istanbul
npm install -g webdriver-manager
npm install -g protractor
npm install -g codeclimate-test-reporter
npm install -g istanbul
