"use strict";
require('zone.js/dist/zone');
require('reflect-metadata');
require('@angular/core');
require('@angular/common');
require('@angular/compiler');
require('@angular/forms');
require('@angular/platform-browser');
require('@angular/platform-browser-dynamic');
require('@angular/http');
require('@angular/router');
require('rxjs');
require('h5webstorage');
require('@ng-bootstrap/ng-bootstrap');
require('angular2-component-outlet-modified/index.js');
require('jquery');
require('tether/dist/js/tether.min.js');
require('bootstrap/dist/js/bootstrap.min.js');
